workspace:
  base: /go
  path: src/app

clone:
  git_clone:
    image: plugins/git
    when:
      event: [ pull_request, tag ]

pipeline:
  pr_test:
    image: golang:1.9-alpine
    commands:
      - go test
    when:
      event: [ pull_request ]

  build:
    image: plugins/docker
    dockerfile: Dockerfile
    registry: docker.c.ehe.io
    repo: docker.c.ehe.io/test1/${DRONE_REPO_NAME}
    insecure: true
    secrets: [ docker_username, docker_password ]
    tags:
      - "${DRONE_TAG}"
      - latest
    when:
      event: [ tag ]
